Stabilizy tests. Part 1
postgrespro/pg_probackup pull request #411
Opened 2021-07-26 04:32 UTC by AndrewBille

2021-07-27 11:24 UTC, kulaginm commented
Выглядит нормально, с Андреем договорились, что ещё пару дней подождём прогонов полных тестов (вдруг ещё что-то понадобится добавить).

2021-08-01 09:58 UTC, gsmol commented
Looks great to me

2021-08-01 09:58 UTC, gsmol requested changes

2021-08-01 09:58 UTC, gsmol commented on tests/Readme.md
> +Run tests that are relied on advanced debugging features. For this mode, pg_probackup should be compiled without optimizations.
Please provide the exact flags to use.

2021-08-03 04:09 UTC, AndrewBille commented on tests/Readme.md
> +Run tests that are relied on advanced debugging features. For this mode, pg_probackup should be compiled without optimizations.
Done!

2021-08-03 15:50 UTC, kulaginm requested changes

2021-08-03 15:50 UTC, kulaginm commented on tests/helpers/ptrack_helpers.py
> +    gdb = 'PGPROBACKUP_GDB' in os.environ and \
Прошу этот кусок сделать более единообразно: или перенести проверку PGPROBACKUP_GDB ниже (в район других проверок env'а) или те вытащить сюда.

2021-08-03 15:50 UTC, kulaginm commented on tests/replica.py
> +            self.skipTest("You must enable PGPROBACKUP_SSH_REMOTE for run this test")
По тексту ниже я не вижу зависимости этого теста от SSH. Нет ли тут ошибки, не избыточна ли эта проверка?

2021-08-03 15:50 UTC, kulaginm commented on tests/show.py
> +            self.skipTest("You must enable PGPROBACKUP_SSH_REMOTE"
Выглядит так, что этот тест должен нормально работать как с SSH, так и без (см. if self.remote: ниже).
Думаю эта проверка тут избыточна

2021-08-03 15:50 UTC, kulaginm commented on tests/show.py
> +            self.skipTest("You must enable PGPROBACKUP_SSH_REMOTE"
И эта проверка тоже кажется не нужна, этот тест тоже должен работать и с ssh и без.

2021-08-03 17:49 UTC, kulaginm commented on tests/show.py
> +            self.skipTest("You must enable PGPROBACKUP_SSH_REMOTE"
Выяснили, как раз должен работать с ssh

2021-08-03 17:49 UTC, kulaginm commented on tests/show.py
> +            self.skipTest("You must enable PGPROBACKUP_SSH_REMOTE"
Выяснили, как раз должен работать с ssh

2021-08-03 18:59 UTC, merged