Small fixes
postgrespro/pg_probackup pull request #546
Opened 2022-10-11 06:37 UTC by funny-falcon

2022-10-11 07:54 UTC, kulaginm commented on src/pg_probackup.c
> +				remote_agent = true;
Я думаю тогда надо дочистить и упоминание условия в config_get_opt() (потому что в случае агента эта функция вроде и не вызывается).

2022-10-11 07:54 UTC, kulaginm commented on src/pg_probackup.c
> +				remote_agent = true;
Я думаю, что тогда нужно дочистить упоминание remote_agent в config_get_opt()

2022-10-11 08:02 UTC, kulaginm requested changes

2022-10-11 08:02 UTC, kulaginm commented on src/data.c
> +		file->crc = fio_get_crc32(from_fullpath, FIO_DB_HOST, false, true);
Я не понимаю, почему тут вызывается с missing_ok = true. Вроде по условию выше как раз файл есть. Прошу оставить комментарий в коде, поясняющий это.

2022-10-11 08:02 UTC, kulaginm commented on src/archive.c
>  		/* TODO: what if one of them goes missing? */
А что с этим комментарием? Он актуален?

2022-10-11 08:35 UTC, kulaginm commented
По поводу введения set_forkname:
Первое, за что зацепился глаз -- это то, что функция глобальная, а мне кажется, что не надо выносить это за пределы src/dir.c.
Предлагаю рассматривать pgFileInit() как некоторый "конструктор" "объектов" pgFile и внести логику/вызов заполнения forkName внутрь этого "конструктора".
Тут остаётся вопрос с обработкой external_dir_num, вижу два варианта:
или заполнять поле forkName в любом случае (так как оно зависит от имени), а обработку external_dir_num оставить на внешнюю логику (которая пользуется pgFile)
или вообще сделать два "конструктора" pgFile, один для создания pgFile из файловой системы (из dir_check_file()), второй из бекапа (get_backup_filelist()).
В любом случае в функции get_backup_filelist() смесь логики чтения файла и заполнения внутренних полей pgFile мне кажется очень некрасивой, хотелось бы побольше убрать внутрь src/dir.c.
Но этом моё имхо, что думаешь?

2022-10-11 08:58 UTC, funny-falcon commented on src/archive.c
>  		/* TODO: what if one of them goes missing? */
Хороший вопрос: могут ли у нас под ногами удалить файл?
Думаю, пока можно "забить" и убрать комментарий.
В целом, даже если мы хотим передавать missing_ok=true , нужно различать "не существовавший" файл и файл с crc==0. Так что, придётся переделывать API.

2022-10-11 10:41 UTC, funny-falcon commented on src/utils/file.c
>  			if (hdr.arg == 1)
! Спасибо!

2022-10-11 10:45 UTC, funny-falcon commented on src/data.c
> +		file->crc = fio_get_crc32(from_fullpath, FIO_DB_HOST, false, true);
ок

2022-10-11 10:46 UTC, funny-falcon commented on src/pg_probackup.c
> +				remote_agent = true;
done

2022-10-11 12:16 UTC, funny-falcon commented
Рефакторинг инициализации pgFile выделен в отдельную задачу.

2022-10-13 09:03 UTC, kulaginm approved these changes

2022-10-13 11:12 UTC, funny-falcon commented
test_basic_ptrack_truncate_replica - локально 20 минут гонял (~25 раз), ни разу не упал

2022-10-13 11:28 UTC, merged